"""Thin DATABASE_URL layer: SQLite, Postgres, and libSQL/Turso."""

from __future__ import annotations

import base64
import json
import logging
import os
import sqlite3
import threading
import urllib.error
import urllib.parse
import urllib.request
from collections.abc import Iterator, Sequence
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Protocol

log = logging.getLogger("cascade.db")

_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  github_user_id INTEGER NOT NULL UNIQUE,
  login TEXT NOT NULL,
  avatar_url TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS installations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  installation_id INTEGER NOT NULL UNIQUE,
  account_login TEXT NOT NULL,
  account_type TEXT NOT NULL,
  installer_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS repos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  installation_id INTEGER NOT NULL REFERENCES installations(installation_id) ON DELETE CASCADE,
  owner TEXT NOT NULL,
  name TEXT NOT NULL,
  github_repo_id INTEGER NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 0,
  UNIQUE (installation_id, github_repo_id)
);

CREATE TABLE IF NOT EXISTS webhook_deliveries (
  id TEXT PRIMARY KEY,
  event TEXT NOT NULL,
  action TEXT,
  repo_full_name TEXT,
  status TEXT NOT NULL,
  reason TEXT,
  received_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_repos_owner_name ON repos(owner, name);
CREATE INDEX IF NOT EXISTS idx_installations_installer ON installations(installer_user_id);
"""

_POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  github_user_id INTEGER NOT NULL UNIQUE,
  login TEXT NOT NULL,
  avatar_url TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS installations (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  installation_id INTEGER NOT NULL UNIQUE,
  account_login TEXT NOT NULL,
  account_type TEXT NOT NULL,
  installer_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS repos (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  installation_id INTEGER NOT NULL REFERENCES installations(installation_id) ON DELETE CASCADE,
  owner TEXT NOT NULL,
  name TEXT NOT NULL,
  github_repo_id INTEGER NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 0,
  UNIQUE (installation_id, github_repo_id)
);

CREATE TABLE IF NOT EXISTS webhook_deliveries (
  id TEXT PRIMARY KEY,
  event TEXT NOT NULL,
  action TEXT,
  repo_full_name TEXT,
  status TEXT NOT NULL,
  reason TEXT,
  received_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_repos_owner_name ON repos(owner, name);
CREATE INDEX IF NOT EXISTS idx_installations_installer ON installations(installer_user_id);
"""

_bootstrapped: set[str] = set()
_boot_lock = threading.Lock()


class UnsupportedDatabase(RuntimeError):
    """DATABASE_URL dialect is unknown, or a driver extra is missing."""


class DatabaseError(RuntimeError):
    """Query or protocol failure on a remote database."""


class DbCursor(Protocol):
    def fetchone(self) -> Any: ...
    def fetchall(self) -> list[Any]: ...


class DbConn(Protocol):
    dialect: str

    def execute(self, sql: str, params: Sequence[Any] = ()) -> DbCursor: ...
    def executescript(self, script: str) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...


def parse_database_url(url: str | None = None) -> tuple[str, str]:
    raw = (url if url is not None else os.environ.get("DATABASE_URL", "")).strip()
    if not raw:
        raw = f"sqlite:///{_default_sqlite_path()}"
    if raw.startswith("sqlite:////"):
        return "sqlite", raw[len("sqlite:///"):]
    if raw.startswith("sqlite:///"):
        return "sqlite", raw[len("sqlite:///"):]
    if raw.startswith("sqlite://"):
        rest = raw[len("sqlite://"):]
        return "sqlite", rest or _default_sqlite_path()
    if raw.startswith("file:"):
        return "sqlite", raw
    if raw.startswith("postgresql://") or raw.startswith("postgres://"):
        return "postgres", raw
    if raw.startswith("libsql://") or raw.startswith("turso://"):
        return "libsql", raw
    if "://" not in raw:
        return "sqlite", raw
    scheme = raw.split("://", 1)[0]
    raise UnsupportedDatabase(
        f"Unsupported DATABASE_URL scheme {scheme!r}. "
        "Use sqlite:///./cascade.db, postgres://, or libsql://."
    )


def _default_sqlite_path() -> str:
    # ponytail: Vercel function fs is read-only except /tmp — ephemeral across instances.
    if os.environ.get("VERCEL"):
        return "/tmp/cascade.db"
    return "./cascade.db"


def _sqlite_file(target: str) -> str:
    if target.startswith("file:") or target == ":memory:" or target.startswith(":memory:"):
        return target
    path = Path(target)
    if not path.is_absolute():
        path = Path.cwd() / path
    path.parent.mkdir(parents=True, exist_ok=True)
    return str(path)


def qmark_to_percent(sql: str) -> str:
    """Translate sqlite-style `?` placeholders to psycopg `%s`."""
    return sql.replace("?", "%s")


def split_sql_statements(script: str) -> list[str]:
    return [part.strip() for part in script.split(";") if part.strip()]


def connect(url: str | None = None) -> Any:
    dialect, target = parse_database_url(url)
    if dialect == "sqlite":
        if os.environ.get("VERCEL") and str(target).startswith("/tmp"):
            log.warning(
                "SQLite on /tmp is ephemeral on Vercel; set DATABASE_URL to "
                "postgres:// or libsql:// for durable hosted state"
            )
        return _connect_sqlite(target)
    if dialect == "postgres":
        return _connect_postgres(target)
    if dialect == "libsql":
        return _connect_libsql(target)
    raise UnsupportedDatabase(
        f"Unsupported DATABASE_URL scheme {dialect!r}. "
        "Use sqlite:///./cascade.db, postgres://, or libsql://."
    )


def _connect_sqlite(target: str) -> sqlite3.Connection:
    path = _sqlite_file(target)
    conn = sqlite3.connect(path, timeout=10, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        conn.execute("PRAGMA journal_mode = WAL")
    except sqlite3.Error:
        pass
    _ensure_schema(conn, path, "sqlite")
    return conn


def _connect_postgres(target: str) -> PostgresConnection:
    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError as e:
        raise UnsupportedDatabase(
            "DATABASE_URL is postgres but psycopg is not installed. "
            "pip install 'psycopg[binary]'."
        ) from e
    dsn = target
    if dsn.startswith("postgres://"):
        dsn = "postgresql://" + dsn[len("postgres://"):]
    raw = psycopg.connect(dsn, row_factory=dict_row)
    conn = PostgresConnection(raw)
    _ensure_schema(conn, target, "postgres")
    return conn


def _connect_libsql(target: str) -> LibsqlConnection:
    pipeline_url, token = parse_libsql_target(target)
    conn = LibsqlConnection(pipeline_url, token)
    _ensure_schema(conn, pipeline_url, "libsql")
    return conn


def parse_libsql_target(target: str) -> tuple[str, str]:
    raw = target
    if raw.startswith("libsql://"):
        raw = "https://" + raw[len("libsql://"):]
    elif raw.startswith("turso://"):
        raw = "https://" + raw[len("turso://"):]
    parts = urllib.parse.urlsplit(raw)
    qs = urllib.parse.parse_qs(parts.query)
    token = ""
    for key in ("authToken", "auth_token", "token"):
        if qs.get(key):
            token = str(qs[key][0])
            break
    if not token:
        token = os.environ.get("TURSO_AUTH_TOKEN", "").strip() or os.environ.get(
            "LIBSQL_AUTH_TOKEN", ""
        ).strip()
    path = parts.path.rstrip("/") or "/v2/pipeline"
    if not path.endswith("/v2/pipeline"):
        path = "/v2/pipeline"
    http_url = urllib.parse.urlunsplit((parts.scheme or "https", parts.netloc, path, "", ""))
    if not token:
        raise UnsupportedDatabase(
            "libsql DATABASE_URL is missing authToken (or TURSO_AUTH_TOKEN / LIBSQL_AUTH_TOKEN)."
        )
    if not parts.netloc:
        raise UnsupportedDatabase("libsql DATABASE_URL is missing a host.")
    return http_url, token


def _ensure_schema(conn: Any, key: str, dialect: str) -> None:
    with _boot_lock:
        if key in _bootstrapped:
            return
        script = _POSTGRES_SCHEMA if dialect == "postgres" else _SCHEMA
        conn.executescript(script)
        conn.commit()
        _bootstrapped.add(key)


def reset_bootstrap_cache() -> None:
    """Test helper — next connect() re-runs CREATE IF NOT EXISTS."""
    with _boot_lock:
        _bootstrapped.clear()


@contextmanager
def get_conn(url: str | None = None) -> Iterator[Any]:
    conn = connect(url)
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def row_to_dict(row: Any | None) -> dict[str, Any] | None:
    if row is None:
        return None
    if isinstance(row, dict):
        return dict(row)
    return {k: row[k] for k in row.keys()}


class PostgresCursor:
    def __init__(self, cursor: Any):
        self._cursor = cursor

    def fetchone(self) -> dict[str, Any] | None:
        row = self._cursor.fetchone()
        if row is None:
            return None
        return dict(row)

    def fetchall(self) -> list[dict[str, Any]]:
        return [dict(row) for row in self._cursor.fetchall()]


class PostgresConnection:
    dialect = "postgres"

    def __init__(self, raw: Any):
        self._raw = raw

    def execute(self, sql: str, params: Sequence[Any] = ()) -> PostgresCursor:
        cursor = self._raw.execute(qmark_to_percent(sql), tuple(params))
        return PostgresCursor(cursor)

    def executescript(self, script: str) -> None:
        for stmt in split_sql_statements(script):
            self._raw.execute(stmt)

    def commit(self) -> None:
        self._raw.commit()

    def rollback(self) -> None:
        self._raw.rollback()

    def close(self) -> None:
        self._raw.close()


class LibsqlCursor:
    def __init__(self, rows: list[dict[str, Any]]):
        self._rows = rows
        self._i = 0

    def fetchone(self) -> dict[str, Any] | None:
        if self._i >= len(self._rows):
            return None
        row = self._rows[self._i]
        self._i += 1
        return row

    def fetchall(self) -> list[dict[str, Any]]:
        rest = self._rows[self._i:]
        self._i = len(self._rows)
        return rest


class LibsqlConnection:
    dialect = "libsql"

    def __init__(self, pipeline_url: str, token: str):
        self._url = pipeline_url
        self._token = token

    def execute(self, sql: str, params: Sequence[Any] = ()) -> LibsqlCursor:
        rows = self._pipeline(sql, params)
        return LibsqlCursor(rows)

    def executescript(self, script: str) -> None:
        for stmt in split_sql_statements(script):
            self.execute(stmt)

    def commit(self) -> None:
        return None

    def rollback(self) -> None:
        return None

    def close(self) -> None:
        return None

    def _pipeline(self, sql: str, params: Sequence[Any]) -> list[dict[str, Any]]:
        body = json.dumps(
            {
                "requests": [
                    {
                        "type": "execute",
                        "stmt": {
                            "sql": sql,
                            "args": [_libsql_arg(p) for p in params],
                        },
                    },
                    {"type": "close"},
                ]
            }
        ).encode()
        req = urllib.request.Request(
            self._url,
            data=body,
            method="POST",
            headers={
                "Authorization": f"Bearer {self._token}",
                "Content-Type": "application/json",
            },
        )
        try:
            with urllib.request.urlopen(req, timeout=20) as resp:
                payload = json.loads(resp.read().decode() or "{}")
        except urllib.error.HTTPError as e:
            detail = e.read().decode()[:400]
            raise DatabaseError(f"libsql HTTP {e.code}: {detail}") from e
        except urllib.error.URLError as e:
            raise DatabaseError(f"libsql unreachable: {e.reason}") from e
        results = payload.get("results") if isinstance(payload, dict) else None
        if not isinstance(results, list) or not results:
            raise DatabaseError("libsql pipeline returned no results")
        first = results[0]
        if isinstance(first, dict) and first.get("type") == "error":
            raise DatabaseError(str(first.get("error") or first))
        response = (first or {}).get("response") if isinstance(first, dict) else None
        result = (response or {}).get("result") if isinstance(response, dict) else None
        if not isinstance(result, dict):
            return []
        cols = [str(c.get("name") or "") for c in (result.get("cols") or [])]
        rows: list[dict[str, Any]] = []
        for raw_row in result.get("rows") or []:
            values = [_libsql_value(cell) for cell in raw_row]
            rows.append({cols[i]: values[i] for i in range(min(len(cols), len(values)))})
        return rows


def _libsql_arg(value: Any) -> dict[str, Any]:
    if value is None:
        return {"type": "null"}
    if isinstance(value, bool):
        return {"type": "integer", "value": "1" if value else "0"}
    if isinstance(value, int):
        return {"type": "integer", "value": str(value)}
    if isinstance(value, float):
        return {"type": "float", "value": str(value)}
    if isinstance(value, (bytes, bytearray)):
        return {"type": "blob", "base64": base64.b64encode(bytes(value)).decode()}
    return {"type": "text", "value": str(value)}


def _libsql_value(cell: Any) -> Any:
    if cell is None:
        return None
    if not isinstance(cell, dict):
        return cell
    kind = cell.get("type")
    if kind == "null":
        return None
    if kind == "integer":
        return int(cell.get("value"))
    if kind == "float":
        return float(cell.get("value"))
    if kind == "blob":
        return base64.b64decode(cell.get("base64") or "")
    return cell.get("value")
